version: "3.3"
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:$SOFTWARE_VERSION_TAG
    restart: always
    ports:
      - 172.17.0.1:18462:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'ADMIN_EMAIL=$ADMIN_EMAIL'
      - 'ENV=$ENV'
      - 'ENABLE_SIGNUP=$ENABLE_SIGNUP'
      - 'SCARF_NO_ANALYTICS=$SCARF_NO_ANALYTICS'
      - 'DO_NOT_TRACK=$DO_NOT_TRACK'
      - 'ANONYMIZED_TELEMETRY=$ANONYMIZED_TELEMETRY'
      - 'WEBUI_NAME=$WEBUI_NAME'
      - 'WEBUI_URL=$WEBUI_URL'
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    extra_hosts:
      - host.docker.internal:host-gateway

  ollama:
    image: ollama/ollama:latest
    restart: always
    expose:
      - 11434:11434
    pull_policy: always
    tty: true
    volumes:
      - ./ollama:/root/.ollama

